version: '3'
services:
  postgres:
    container_name: database
    image: postgres:13-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app
  # nestjs:
  #   container_name: nestapp
  #   env_file:
  #     - .env
  #   volumes:
  #     - nestapp:/usr/src/app
  #   networks:
  #     - app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - postgres
  #   expose:
  #     - "3000"

volumes:
  postgres:
    name: nest-init-docker-db
  # nestapp:
  #   name: nestapp

networks:
  app:
