version: '3'
services:
  postgres:
    container_name: database
    image: postgres:13-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - transendance
  nestjs:
    container_name: nestapp
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./app:/usr/src/app
    networks:
      - transendance

volumes:
  postgres:
    name: nest-init-docker-db
  nestapp:
    name: nestapp

networks:
  transendance:
    name: transendance
